name: e_commerce
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  # HELPER
  equatable: ^2.0.3
  logger: ^1.1.0
  http: ^0.13.4
  shared_preferences: ^2.0.11
  get_it: ^7.2.0

  # WIDGET
  fluttertoast: ^8.0.8
  flutter_dialogs: ^2.1.1

  # STATE MANAGEMENT
  flutter_bloc: ^8.0.0
  auto_route: ^3.2.0

  # FIREBASE
  # GITHUB

  # FLUTTER
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  auto_route_generator: ^3.2.0

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Metropolis
      fonts:
        - asset: assets/fonts/metropolis/Metropolis-Medium.otf
          weight: 700
