// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQezG2eJiq3kHv6nH4_rMDWFbSMiByYLY',
    appId: '1:439166592662:web:0c7e5fdd4f4fba4c6c04b7',
    messagingSenderId: '439166592662',
    projectId: 'e-commerce-c1119',
    authDomain: 'e-commerce-c1119.firebaseapp.com',
    storageBucket: 'e-commerce-c1119.appspot.com',
    measurementId: 'G-L1CS5FV35B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8Kj8IgQJzr4llk4kbfib7_SLu3y7zVFo',
    appId: '1:439166592662:android:f62453ab796b72e36c04b7',
    messagingSenderId: '439166592662',
    projectId: 'e-commerce-c1119',
    storageBucket: 'e-commerce-c1119.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4xcz6Vq2524Y5m2qp6HjdYNdxg4E_JZQ',
    appId: '1:439166592662:ios:70e19d9513e9dc906c04b7',
    messagingSenderId: '439166592662',
    projectId: 'e-commerce-c1119',
    storageBucket: 'e-commerce-c1119.appspot.com',
    iosClientId: '439166592662-9j6ouruej75ipo1i86l9s16f1j0nc40u.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce',
  );
}
